name: kids_bids
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  google_fonts: ^4.0.3
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.11
  fluttertoast: ^8.1.3
  shimmer: ^2.0.0
  auto_size_text: ^3.0.0
  get: ^4.6.5
  lottie: ^2.2.0
  syncfusion_flutter_charts: ^19.2.55
  pie_chart: ^5.3.2
  carousel_slider: ^4.2.1
  youtube_player_iframe: ^4.0.4
  webview_flutter_web: ^0.2.2+1
  webviewx_plus: ^0.3.3
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  intl: ^0.17.0
  shared_preferences: ^2.0.18
  painter: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  audioplayers: ^3.0.0
  go_router: ^6.0.1
  logging: ^1.1.0
  provider: ^6.0.2
  firebase_crashlytics: ^3.3.1
  flutter_inappwebview: ^5.7.2+3
  
  


flutter:
  uses-material-design: true
  assets:
      - assets/icon/
      - assets/logo/
      - assets/image/
      - assets/images/
      - assets/items/
      - assets/fruits/
      - assets/shape/
      - assets/lotties/
 

  